### ISSUE TITLE
Bug: Web Platform - CSS Error on dev build

### ISSUE THREAD

**Issue by d3viant0ne** [DeviantJS/angular2-seed#2]
Task: `npm run web.build.dev`
```
[22:10:44] Error: Cannot find module 'zone.js/dist/zone.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.resolve (internal/module.js:27:19)
    at web.config.ts:479:59
    at Array.forEach (native)
    at normalizeDependencies (web.config.ts:479:6)
    at ProjectWebConfig.Object.defineProperty.get [as DEPENDENCIES] (web.config.ts:293:12)
    at getExternalCss (web.build.html_css.ts:137:10)
    at processExternalCss (web.build.html_css.ts:125:19)
    at processExternalStylesheets (web.build.html_css.ts:118:50)
    at module.exports (web.build.html_css.ts:143:73)
[22:10:44] 'web.build.dev' errored after 24 s
[22:10:44] Error in plugin 'run-sequence(web.build.html_css)'
Message:
    web.build.html_css catch

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: /Users/d3viant0ne/Projects/deviantjs/angular2-seed/src/web/dist/dev/node_modules/systemjs/test/tests/test.css:1:1: Unknown word
this is  #css
```

**Comment by d3viant0ne** [comment]
Problem is somewhere in the `web.config.ts` when executing `getExternalCss()` from `web.build.html.css.ts`
