### ISSUE TITLE
Bug: Web Platform - Custom rules on Prod build

### ISSUE THREAD

**Issue by d3viant0ne** [DeviantJS/angular2-seed#3]
```
[20:25:28] Starting 'web.tslint'...

/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/tslint/lib/configuration.js:181
            throw new Error("Could not find custom rule directory: " + directory);
                  ^
Error: Could not find custom rule directory: /Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/codelyzer
    at Object.getRulesDirectories (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/tslint/lib/configuration.js:181:19)
    at findRule (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/tslint/lib/ruleLoader.js:42:39)
    at Object.loadRules (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/tslint/lib/ruleLoader.js:14:24)
    at Linter.lint (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/tslint/lib/tslint.js:25:44)
    at /Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/gulp-tslint/index.js:96:34
    at respond (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/rcloader/index.js:75:7)
    at respond (/Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/rcfinder/index.js:140:7)
    at /Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/rcfinder/index.js:124:17
    at /Users/d3viant0ne/Projects/deviantjs/angular2-seed/node_modules/rcfinder/index.js:77:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by d3viant0ne** [comment]
Resolved with 1fbb007
